### ISSUE TITLE
ERROR: frame_mbs_only_flag

### ISSUE THREAD

**Issue by zhfnjust** [oneam/h264bsd#15]
hi, i got a error when i use this lib 

`ERROR: frame_mbs_only_flag,`
`ERROR: SEQ_PARAM_SE, `

**Comment by fralonra** [comment]
the latter one should be `ERROR: SEQ_PARAM_SET`

**Comment by oneam** [comment]
This decoder only supports constrained baseline profile of H.264 (https://en.wikipedia.org/wiki/Advanced_Video_Coding#Profiles)

frame_mbs_only_flag indicates that the encoding may support interlaced video, which is not supported by the constrained baseline profile.
