### ISSUE TITLE
How to build this project from Rakefile

### ISSUE THREAD

**Issue by myjimmy** [oneam/h264bsd#19]
This isn't an issue.
I need to rebuild this project because there is a problem when using several projects built by [emscripten](http://emscripten.org/).
The cause is because those projects use the default namespace 'Module' of emscripten.
So, I need to change the default namespace and rebuild this project.

I found the `Rakefile` file in `wasm` folder and I could guess that this file is used to build the project.
Unfortunately, I don't know anything about `Rakefile`.

@oneam please tell me how to build this project by using `Rakefile`.
Also, I need the version of emscripten as well.
I need to rebuild this project on Ubuntu 18.04 64bit.

**Comment by oneam** [comment]
I used Ruby Rake as a build tool for the project since I find it simple and clear.

You should be able to get everything you need to build the project on Ubuntu 18 using:
```
sudo apt update
sudo apt install rake emscripten libjs-uglify
cd wasm/
rake
```

(Note: I haven't tested this myself)
