### ISSUE TITLE
Cant play movie twice

### ISSUE THREAD

**Issue by BleuBleu** [oneam/h264bsd#6]
Hi!

I am experimenting with your library for H264 decoding. The first time the stream is played, it works really well, but I'm having a problem playing the same stream twice (to simulate looping). The problem seems to come from h264bsdExtractNalUnit which modifies the input stream, possibly to try to fix malformed data. The stream was encoded with x264 and plays well in all video players i have tried. 

Do you know of any workaround to fix this issue? Thanks!

-Mat

[out.zip](https://github.com/oneam/h264bsd/files/346832/out.zip)

**Comment by oneam** [comment]
The decoder modifies the bytes that are sent to it. It's an unfortunate side-effect that I have not spent any time looking into.

What I've done in the test applications is to keep a gold master copy of the input stream, then copy it to a decode stream that can be modified by the decoder.


Here's the Javascript example:
https://github.com/oneam/h264bsd/blob/master/js/test.html#L50

IOS:
https://github.com/oneam/h264bsd/blob/master/ios/test/h264bsd%20Test/ViewController.m#L130
