### ISSUE TITLE
Decoder Error

### ISSUE THREAD

**Issue by AmdEagle** [oneam/h264bsd#7]
I am trying to decode stream of h264 NALUnits ( Uint8Array ).
i get the following error in the console.

![image](https://cloud.githubusercontent.com/assets/6722962/23840559/1c4c2910-07e1-11e7-96bf-07cc78757a77.png)

**Comment by oneam** [comment]
That error appears when the decoder checks that the stream is Constrained Baseline Profile (CBP) compliant.

Are you sure your input stream has been encoded using baseline profile?
(Main and high profile are not supported by the decoder)

**Comment by AmdEagle** [comment]
Oh my stream is in main line profile. any decoder that is able to decode main line profile ?

**Comment by SUGE2016** [comment]
why this decoder support "baseline profile" only? what limitations

**Comment by oneam** [comment]
The decoder itself was pulled from the Android open source project. It never had support for the features available in the H.264 main profile.

I didn't create the decoder itself. I simply wrapped it in a Foreign Function Interface and made it available on a few platforms.
